# Header
menu:
  Home: /
  Archives: /archives/
  Java Tutorials: /java/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# archive widget behavior
archive_type: 'monthly'
archive_count: true

# Miscellaneous
google_analytics: UA-599349-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
